version: '3.8'

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nemory-landing
    ports:
      - '8081:3000'
    restart: unless-stopped
    environment:
      NODE_ENV: production
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3000/']
      interval: 30s
      timeout: 5s
      retries: 5
